<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization/messages_*.json" LogicalName="Kela.Web.Localization.%(Filename).json" />
  </ItemGroup>

  <Target Name="BuildTailwindCss" BeforeTargets="BeforeBuild">
    <Exec Command="npm install --prefix $(MSBuildProjectDirectory)" />
    <Exec Command="npm run --prefix $(MSBuildProjectDirectory) build:css" />
  </Target>

</Project>
