@Kela.Api_HostAddress = http://localhost:5117

### Kullanıcı oluştur
POST {{Kela.Api_HostAddress}}/api/users
Content-Type: application/json

{
  "firstName": "Ahmet",
  "lastName": "Yılmaz",
  "email": "ahmet@example.com",
  "password": "sifre123",
  "role": 3
}

### Login
POST {{Kela.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "ahmet@example.com",
  "password": "sifre123"
}

### Logout
POST {{Kela.Api_HostAddress}}/api/auth/logout

### Kullanıcı listesi (sayfalı)
GET {{Kela.Api_HostAddress}}/api/users?page=1&pageSize=20

### Sınıf (şube) listesi (sayfalı)
GET {{Kela.Api_HostAddress}}/api/sections?page=1&pageSize=20
